name = "StanMCMCChains"
uuid = "7c54f3ea-f601-52d0-b368-23ec931b1f8b"
authors = ["StanJulia <goedman@mac.com>"]
version = "0.1.0"

[deps]
CmdStan = "593b3428-ca2f-500c-ae53-031589ec8ddd"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
MCMCChain = "743f40f2-f054-542e-92b9-3abbf60d0031"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
